<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerOctK0ye\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOctK0ye/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOctK0ye.legacy');
=======
if (\class_exists(\ContainerVQB23Qm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVQB23Qm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVQB23Qm.legacy');
>>>>>>> db12c52c2aab90629ff7231a2f093fd01c4b30c8

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerOctK0ye\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOctK0ye\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OctK0ye',
    'container.build_id' => '6fb0eeea',
    'container.build_time' => 1646866276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOctK0ye');
=======
    \class_alias(\ContainerVQB23Qm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVQB23Qm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VQB23Qm',
    'container.build_id' => '2679d66b',
    'container.build_time' => 1646856144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVQB23Qm');
>>>>>>> db12c52c2aab90629ff7231a2f093fd01c4b30c8
