<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3WhqBgR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3WhqBgR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3WhqBgR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3WhqBgR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3WhqBgR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3WhqBgR',
    'container.build_id' => '9a90eced',
    'container.build_time' => 1646787045,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3WhqBgR');
