<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], []],
    'front' => [[], ['_controller' => 'App\\Controller\\FrontController::index'], [], [['text', '/front']], [], []],
    'livraison_controlleur' => [[], ['_controller' => 'App\\Controller\\LivraisonControlleur::index'], [], [['text', '/livraison/controlleur']], [], []],
    'r_list' => [[], ['_controller' => 'App\\Controller\\LivraisonControlleur::afficher'], [], [['text', '/livraison/list']], [], []],
    'r_delete' => [['id'], ['_controller' => 'App\\Controller\\LivraisonControlleur::Supprimer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/livraison/delete']], [], []],
    'r_add' => [[], ['_controller' => 'App\\Controller\\LivraisonControlleur::Add'], [], [['text', '/livraison/add']], [], []],
    'r_update' => [['id'], ['_controller' => 'App\\Controller\\LivraisonControlleur::Update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/livraison/update']], [], []],
    'vehicule' => [[], ['_controller' => 'App\\Controller\\VehiculeController::index'], [], [['text', '/vehicule']], [], []],
    'veh_list' => [[], ['_controller' => 'App\\Controller\\VehiculeController::afficher'], [], [['text', '/vehicule/list']], [], []],
    'veh_delete' => [['id'], ['_controller' => 'App\\Controller\\VehiculeController::Supprimer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/vehicule/delete']], [], []],
    'voi_add' => [[], ['_controller' => 'App\\Controller\\VehiculeController::AddVoiture'], [], [['text', '/voiture/add']], [], []],
    'voi_update' => [['id'], ['_controller' => 'App\\Controller\\VehiculeController::Update'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/voiture/update']], [], []],
    'mot_add' => [[], ['_controller' => 'App\\Controller\\VehiculeController::AddMoto'], [], [['text', '/moto/add']], [], []],
    'mot_update' => [['id'], ['_controller' => 'App\\Controller\\VehiculeController::UpdateMoto'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/moto/update']], [], []],
    'cam_add' => [[], ['_controller' => 'App\\Controller\\VehiculeController::AddCamion'], [], [['text', '/camion/add']], [], []],
    'cam_update' => [['id'], ['_controller' => 'App\\Controller\\VehiculeController::UpdateCamion'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/camion/update']], [], []],
];
